"use client";
import { useEffect, useState } from "react";
import dynamic from "next/dynamic";
import MouseTethers from "@/components/mouse-tethers";
const Scene = dynamic(() => import("@/components/scene"), { ssr: false });
const projects = [
  ["01","Dr. Yassine Kallali","A modern multilingual healthcare platform designed to present medical services and guide international patients through their journey.","https://www.dryassinekallali.com/en","/project-previews/dr-yassine-kallali.png"],
  ["02","BMS Global Trade","A corporate web experience built to present BMS Global's international trade activities, services, and business expertise.","https://www.bmsglobaltradecompany.com/en","/project-previews/bms-global-trade.png"],
  ["03","UEM","A product-focused digital experience combining e-commerce, product discovery, content, and customer interaction.","https://uem.tn","/project-previews/uem.png"],
  ["04","Terra Dora","A premium digital identity for a Tunisian olive oil exporter, focused on quality, traceability, and international distribution.","https://terradoraoliveoil.com","/project-previews/terra-dora.png"],
  ["05","JMA Business Consulting","A professional corporate platform presenting consulting services, investment opportunities, and business expertise.","https://jmabuzness.com/en","/project-previews/jma-business.png"],
  ["06","MBC Renov","A modern web presence designed to showcase renovation services, completed work, and the company's expertise.","https://www.mbcrenov.com","/project-previews/mbc-renov.png"],
  ["07","iOS 4 Move","A transportation platform focused on an intuitive booking experience for private transfers and travel services.","https://www.ios4move.com/en","/project-previews/ios4move.png"],
];
const experience = [
  ["2025 — 2026", "Job", "Duality Agency"],
  ["2025", "Internship", "Duality Agency"],
  ["2024", "Internship", "IMSET"],
  ["2021", "Brevet de Technicien Professionnel", "IMSET · Studies"],
];
const technologies = ["JavaScript","React","Next.js","NestJS","Node.js","PostgreSQL","MongoDB","Docker","Git","GitHub"];
const colors = {JavaScript:"#e7bd35",React:"#54c9ec","Next.js":"#d7e2e5",NestJS:"#e34955","Node.js":"#65aa5a",PostgreSQL:"#659aca",MongoDB:"#4e9d6c",Docker:"#4d9be8",Git:"#e17a4d",GitHub:"#a78bcb"};
const copy = {
  en: {
    nav: ["Work", "About", "Experience", "Contact"], download: "Download CV", available: "Available for select work", role: "Full-stack developer / Tunisia", hero: <>I build modern web applications<br/>and digital experiences.</>, viewWork: "View work", scroll: "Scroll to explore",
    introLabel: "01 / An introduction", introTitle: <>A thoughtful blend<br/>of <em>logic</em> and feeling.</>, introText: "I make the systems behind a product feel as considered as the experience in front of it. From an early idea to a robust release, I care about the whole picture.",
    workLabel: "02 / Selected work", liveSite: "Live website", viewProject: "View project", visit: "Visit", preview: "Homepage preview of",
    aboutLabel: "03 / About Sadok", aboutTitle: <>Built for people,<br/>shaped by <em>systems.</em></>, aboutText: "I’m a full-stack developer focused on modern web applications. I enjoy moving between frontend craft, reliable backend logic, APIs, databases, and the cloud—bringing every layer together into a calm, useful whole.",
    experienceLabel: "04 / Experience", experienceTitle: <>The road<br/>so <em>far.</em></>, technologyLabel: "05 / Technologies", technologyTitle: <>Tools I make<br/><em>things with.</em></>, toolkit: "Technology toolkit",
    contactLabel: "06 / Get in touch", contactTitle: <>Let’s build<br/><em>something.</em></>, email: "Email me", footer: "Sadok Acacha / Full-stack developer",
    projects: ["A modern multilingual healthcare platform designed to present medical services and guide international patients through their journey.", "A corporate web experience built to present BMS Global's international trade activities, services, and business expertise.", "A product-focused digital experience combining e-commerce, product discovery, content, and customer interaction.", "A premium digital identity for a Tunisian olive oil exporter, focused on quality, traceability, and international distribution.", "A professional corporate platform presenting consulting services, investment opportunities, and business expertise.", "A modern web presence designed to showcase renovation services, completed work, and the company's expertise.", "A transportation platform focused on an intuitive booking experience for private transfers and travel services."],
    roles: ["Job", "Internship", "Internship", "Professional Technician Certificate"],
  },
  fr: {
    nav: ["Projets", "À propos", "Expérience", "Contact"], download: "Télécharger le CV", available: "Disponible pour des projets sélectionnés", role: "Développeur full-stack / Tunisie", hero: <>Je crée des applications web modernes<br/>et des expériences numériques.</>, viewWork: "Voir les projets", scroll: "Faire défiler",
    introLabel: "01 / Une introduction", introTitle: <>Un équilibre réfléchi<br/>entre <em>logique</em> et émotion.</>, introText: "Je conçois les systèmes derrière un produit avec autant de soin que l’expérience qui se trouve devant. De la première idée à une mise en ligne solide, je m’intéresse à l’ensemble.",
    workLabel: "02 / Projets sélectionnés", liveSite: "Site en ligne", viewProject: "Voir le projet", visit: "Visiter", preview: "Aperçu de la page d’accueil de",
    aboutLabel: "03 / À propos de Sadok", aboutTitle: <>Pensé pour les personnes,<br/>façonné par les <em>systèmes.</em></>, aboutText: "Je suis développeur full-stack, spécialisé dans les applications web modernes. J’aime passer de la précision du frontend à la logique fiable du backend, aux API, bases de données et au cloud, pour réunir chaque couche dans un ensemble clair et utile.",
    experienceLabel: "04 / Expérience", experienceTitle: <>Le chemin<br/>parcouru <em>jusqu’ici.</em></>, technologyLabel: "05 / Technologies", technologyTitle: <>Les outils avec<br/>lesquels je <em>crée.</em></>, toolkit: "Boîte à outils technologique",
    contactLabel: "06 / Me contacter", contactTitle: <>Créons quelque<br/>chose <em>ensemble.</em></>, email: "M’écrire", footer: "Sadok Acacha / Développeur full-stack",
    projects: ["Une plateforme de santé multilingue moderne, conçue pour présenter les services médicaux et accompagner les patients internationaux tout au long de leur parcours.", "Une expérience web corporate conçue pour présenter les activités de commerce international, les services et l’expertise de BMS Global.", "Une expérience numérique centrée sur le produit, réunissant e-commerce, découverte de produits, contenu et interaction client.", "Une identité numérique premium pour un exportateur tunisien d’huile d’olive, axée sur la qualité, la traçabilité et la distribution internationale.", "Une plateforme corporate professionnelle présentant des services de conseil, des opportunités d’investissement et une expertise métier.", "Une présence web moderne conçue pour mettre en valeur les services de rénovation, les réalisations et l’expertise de l’entreprise.", "Une plateforme de transport axée sur une réservation intuitive pour les transferts privés et les services de voyage."],
    roles: ["Poste", "Stage", "Stage", "Brevet de technicien professionnel"],
  },
};
function Link({href,children,className=""}) { return <a href={href} className={`magnetic-link ${className}`}>{children}<span aria-hidden="true">↗</span></a>; }
export default function Portfolio() {
  const [activeTech,setActiveTech] = useState("React");
  const [language,setLanguage] = useState("en");
  const t = copy[language];
  const changeLanguage = (nextLanguage) => { setLanguage(nextLanguage); document.documentElement.lang = nextLanguage; window.localStorage.setItem("portfolio-language", nextLanguage); };
  useEffect(() => { const move = (e) => { document.documentElement.style.setProperty("--mouse-x",`${e.clientX}px`); document.documentElement.style.setProperty("--mouse-y",`${e.clientY}px`); }; window.addEventListener("pointermove",move,{passive:true}); return () => window.removeEventListener("pointermove",move); },[]);
  useEffect(() => { const savedLanguage = window.localStorage.getItem("portfolio-language"); if (savedLanguage === "fr" || savedLanguage === "en") { setLanguage(savedLanguage); document.documentElement.lang = savedLanguage; } }, []);
  useEffect(() => { const stages=document.querySelectorAll(".space-stage"); const observer=new IntersectionObserver((entries)=>entries.forEach((entry)=>{if(entry.isIntersecting)entry.target.classList.add("space-visible");}),{threshold:0,rootMargin:"0px 0px -10% 0px"}); stages.forEach((stage)=>observer.observe(stage)); return()=>observer.disconnect(); },[]);
  return <main><div className="scene-wrap" aria-hidden="true"><Scene /></div><MouseTethers />
    <header className="site-header"><a href="#top" className="wordmark">SADOK<br/>ACACHA</a><nav aria-label="Primary navigation"><a href="#work">{t.nav[0]}</a><a href="#about">{t.nav[1]}</a><a href="#experience">{t.nav[2]}</a><a href="#contact">{t.nav[3]}</a></nav><div className="header-actions"><div className="language-switch" aria-label="Language"><button type="button" className={language === "en" ? "active" : ""} aria-pressed={language === "en"} onClick={()=>changeLanguage("en")}>EN</button><span>/</span><button type="button" className={language === "fr" ? "active" : ""} aria-pressed={language === "fr"} onClick={()=>changeLanguage("fr")}>FR</button></div><a className="cv-link" href="/Sadok-Acacha-CV.pdf" download>{t.download} <span>↓</span></a></div></header>
    <section id="top" className="hero section-shell"><div className="eyebrow hero-index"><span className="pulse"/> {t.available}</div><div className="hero-copy"><p className="eyebrow">{t.role}</p><h1>Sadok<br/><em>Acacha</em></h1><div className="hero-bottom"><p>{t.hero}</p><a href="#work" className="work-link">{t.viewWork} <span>↓</span></a></div></div><p className="scroll-note">{t.scroll} <span>↓</span></p></section>
    <section className="intro section-shell space-stage" aria-labelledby="intro-heading"><p className="eyebrow">{t.introLabel}</p><h2 id="intro-heading">{t.introTitle}</h2><p className="intro-text">{t.introText}</p></section>
    <section id="work" className="work section-shell space-stage" aria-labelledby="work-heading"><div className="work-heading"><p className="eyebrow" id="work-heading">{t.workLabel}</p></div><div className="projects">{projects.map(([number,title,,url,image],index)=><article className="project-card" key={title}><a className="project-art" href={url} target="_blank" rel="noreferrer" aria-label={`${t.visit} ${title}`}><img src={image} alt={`${t.preview} ${title}`}/><span className="project-no">{number}</span><span className="project-mark">SA</span></a><div className="project-info"><h3>{title}</h3><p className="project-description">{t.projects[index]}</p><div className="project-meta"><span>{t.liveSite}</span><a href={url} target="_blank" rel="noreferrer">{t.viewProject} <b>↗</b></a></div></div></article>)}</div></section>
    <section id="about" className="about section-shell space-stage" aria-labelledby="about-heading"><div className="portal"><div className="portal-inner"/></div><div className="about-copy"><p className="eyebrow">{t.aboutLabel}</p><h2 id="about-heading">{t.aboutTitle}</h2><p>{t.aboutText}</p><Link href="/Sadok-Acacha-CV.pdf" className="outline-button">{t.download}</Link></div></section>
    <section id="experience" className="experience section-shell space-stage" aria-labelledby="experience-heading"><div className="section-heading"><p className="eyebrow">{t.experienceLabel}</p><h2 id="experience-heading">{t.experienceTitle}</h2></div><div className="timeline">{experience.map(([year,role,place],index)=><article className="timeline-entry" key={`${year}-${role}`}><p className="year">{year}</p><div><h3>{t.roles[index]}</h3><p className="timeline-place">{place}</p></div></article>)}</div></section>
    <section className="technology section-shell space-stage" aria-labelledby="technology-heading"><div className="section-heading"><p className="eyebrow">{t.technologyLabel}</p><h2 id="technology-heading">{t.technologyTitle}</h2></div><div className="tech-stage"><div className="tech-carousel" role="list" aria-label={t.toolkit}>{technologies.map((tech,i)=><button type="button" role="listitem" onClick={()=>setActiveTech(tech)} onMouseEnter={()=>setActiveTech(tech)} onFocus={()=>setActiveTech(tech)} className={`tech-planet-card ${activeTech===tech?"active":""}`} style={{"--planet-color":colors[tech]}} key={tech}><span className={`tech-planet planet-variant-${i % 5}`} aria-hidden="true"><i/><b/></span><span className="tech-index">{String(i+1).padStart(2,"0")}</span><span className="tech-name">{tech}</span></button>)}</div></div></section>
    <section id="contact" className="contact section-shell space-stage" aria-labelledby="contact-heading"><p className="eyebrow">{t.contactLabel}</p><h2 id="contact-heading">{t.contactTitle}</h2><div className="contact-links"><Link href="mailto:hello@sadokacacha.com">{t.email}</Link><Link href="https://github.com/">GitHub</Link><Link href="https://linkedin.com/">LinkedIn</Link></div><footer><span>{t.footer}</span><span>© 2026</span></footer></section>
  </main>;
}
