"use client";
import { useEffect, useState } from "react";
import dynamic from "next/dynamic";
import MouseTethers from "@/components/mouse-tethers";
const Scene = dynamic(() => import("@/components/scene"), { ssr: false });
const projects = [
  ["01","Dr. Yassine Kallali","A modern multilingual healthcare platform designed to present medical services and guide international patients through their journey.","https://www.dryassinekallali.com/en","/project-previews/dr-yassine-kallali.png"],
  ["02","BMS Global Trade","A corporate web experience built to present BMS Global's international trade activities, services, and business expertise.","https://www.bmsglobaltradecompany.com/en","/project-previews/bms-global-trade.png"],
  ["03","UEM","A product-focused digital experience combining e-commerce, product discovery, content, and customer interaction.","https://uem.tn","/project-previews/uem.png"],
  ["04","Terra Dora","A premium digital identity for a Tunisian olive oil exporter, focused on quality, traceability, and international distribution.","https://terradoraoliveoil.com","/project-previews/terra-dora.png"],
  ["05","JMA Business Consulting","A professional corporate platform presenting consulting services, investment opportunities, and business expertise.","https://jmabuzness.com/en","/project-previews/jma-business.png"],
  ["06","MBC Renov","A modern web presence designed to showcase renovation services, completed work, and the company's expertise.","https://www.mbcrenov.com","/project-previews/mbc-renov.png"],
  ["07","iOS 4 Move","A transportation platform focused on an intuitive booking experience for private transfers and travel services.","https://www.ios4move.com/en","/project-previews/ios4move.png"],
];
const experience = [["2026","Full-stack developer","Building clear, dependable digital products from the interface through to the infrastructure.","React · Next.js · Node.js"],["2025","Independent product work","Partnering with teams to shape useful web applications and improve existing systems.","JavaScript · APIs · PostgreSQL"],["2024","Web development","Developing responsive experiences with a focus on thoughtful details and performance.","HTML · CSS · Git"]];
const technologies = ["JavaScript","React","Next.js","NestJS","Node.js","PostgreSQL","MongoDB","Docker","Git","GitHub"];
const colors = {JavaScript:"#e7bd35",React:"#54c9ec","Next.js":"#d7e2e5",NestJS:"#e34955","Node.js":"#65aa5a",PostgreSQL:"#659aca",MongoDB:"#4e9d6c",Docker:"#4d9be8",Git:"#e17a4d",GitHub:"#a78bcb"};
function Link({href,children,className=""}) { return <a href={href} className={`magnetic-link ${className}`}>{children}<span aria-hidden="true">↗</span></a>; }
export default function Portfolio() {
  const [activeTech,setActiveTech] = useState("React");
  useEffect(() => { const move = (e) => { document.documentElement.style.setProperty("--mouse-x",`${e.clientX}px`); document.documentElement.style.setProperty("--mouse-y",`${e.clientY}px`); }; window.addEventListener("pointermove",move,{passive:true}); return () => window.removeEventListener("pointermove",move); },[]);
  useEffect(() => { const stages=document.querySelectorAll(".space-stage"); const observer=new IntersectionObserver((entries)=>entries.forEach((entry)=>{if(entry.isIntersecting)entry.target.classList.add("space-visible");}),{threshold:0,rootMargin:"0px 0px -10% 0px"}); stages.forEach((stage)=>observer.observe(stage)); return()=>observer.disconnect(); },[]);
  return <main><div className="scene-wrap" aria-hidden="true"><Scene /></div><MouseTethers />
    <header className="site-header"><a href="#top" className="wordmark">SADOK<br/>ACACHA</a><nav aria-label="Primary navigation"><a href="#work">Work</a><a href="#about">About</a><a href="#experience">Experience</a><a href="#contact">Contact</a></nav><a className="cv-link" href="/Sadok-Acacha-CV.pdf" download>Download CV <span>↓</span></a></header>
    <section id="top" className="hero section-shell"><div className="eyebrow hero-index"><span className="pulse"/> Available for select work</div><div className="hero-copy"><p className="eyebrow">Full-stack developer / Tunisia</p><h1>Sadok<br/><em>Acacha</em></h1><div className="hero-bottom"><p>I build modern web applications<br/>and digital experiences.</p><a href="#work" className="work-link">View work <span>↓</span></a></div></div><p className="scroll-note">Scroll to explore <span>↓</span></p></section>
    <section className="intro section-shell space-stage" aria-labelledby="intro-heading"><p className="eyebrow">01 / An introduction</p><h2 id="intro-heading">A thoughtful blend<br/>of <em>logic</em> and feeling.</h2><p className="intro-text">I make the systems behind a product feel as considered as the experience in front of it. From an early idea to a robust release, I care about the whole picture.</p></section>
    <section id="work" className="work section-shell space-stage" aria-labelledby="work-heading"><div className="work-heading"><p className="eyebrow" id="work-heading">02 / Selected work</p></div><div className="projects">{projects.map(([number,title,description,url,image])=><article className="project-card" key={title}><a className="project-art" href={url} target="_blank" rel="noreferrer" aria-label={`Visit ${title}`}><img src={image} alt={`Homepage preview of ${title}`}/><span className="project-no">{number}</span><span className="project-mark">SA</span></a><div className="project-info"><h3>{title}</h3><p className="project-description">{description}</p><div className="project-meta"><span>Live website</span><a href={url} target="_blank" rel="noreferrer">View project <b>↗</b></a></div></div></article>)}</div></section>
    <section id="about" className="about section-shell space-stage" aria-labelledby="about-heading"><div className="portal"><div className="portal-inner"/></div><div className="about-copy"><p className="eyebrow">03 / About Sadok</p><h2 id="about-heading">Built for people,<br/>shaped by <em>systems.</em></h2><p>I’m a full-stack developer focused on modern web applications. I enjoy moving between frontend craft, reliable backend logic, APIs, databases, and the cloud—bringing every layer together into a calm, useful whole.</p><Link href="/Sadok-Acacha-CV.pdf" className="outline-button">Download CV</Link></div></section>
    <section id="experience" className="experience section-shell space-stage" aria-labelledby="experience-heading"><div className="section-heading"><p className="eyebrow">04 / Experience</p><h2 id="experience-heading">The road<br/>so <em>far.</em></h2></div><div className="timeline">{experience.map(([year,role,text,stack])=><article className="timeline-entry" key={year}><p className="year">{year}</p><div><h3>{role}</h3><p>{text}</p><span>{stack}</span></div><b>↗</b></article>)}</div></section>
    <section className="technology section-shell space-stage" aria-labelledby="technology-heading"><div className="section-heading"><p className="eyebrow">05 / Technologies</p><h2 id="technology-heading">Tools I make<br/><em>things with.</em></h2></div><div className="tech-stage"><div className="tech-carousel" role="list" aria-label="Technology toolkit">{technologies.map((tech,i)=><button type="button" role="listitem" onClick={()=>setActiveTech(tech)} onMouseEnter={()=>setActiveTech(tech)} onFocus={()=>setActiveTech(tech)} className={`tech-planet-card ${activeTech===tech?"active":""}`} style={{"--planet-color":colors[tech]}} key={tech}><span className="tech-planet" aria-hidden="true"><i/><b/></span><span className="tech-index">{String(i+1).padStart(2,"0")}</span><span className="tech-name">{tech}</span></button>)}</div></div></section>
    <section id="contact" className="contact section-shell space-stage" aria-labelledby="contact-heading"><p className="eyebrow">06 / Get in touch</p><h2 id="contact-heading">Let’s build<br/><em>something.</em></h2><div className="contact-links"><Link href="mailto:hello@sadokacacha.com">Email me</Link><Link href="https://github.com/">GitHub</Link><Link href="https://linkedin.com/">LinkedIn</Link></div><footer><span>Sadok Acacha / Full-stack developer</span><span>© 2026</span></footer></section>
  </main>;
}
